### ISSUE TITLE
How to replace the urls back to the original text?

### ISSUE THREAD

**Issue by onhate** [sindresorhus/urls-md#8]
I would like to "enrich" the inputed text when converting to markdown and for that I would need to replace the raw links with the markdown formatted content, how would you do that?

**Comment by sindresorhus** [comment]
That's not something this package was intended for. However, there's very little code: https://github.com/sindresorhus/urls-md/blob/master/index.js You could easily modify it to your own needs, for example doing a URL string replace instead of just returning the Markdown elements.

**Comment by onhate** [comment]
Thanks @sindresorhus
